home:
  path: /
  controller: App\Controller\HomeController::index

property.index:
  path: /biens
  controller: App\Controller\PropertyController::index

controllers:
  resource: ../src/Controller/
  type: attribute
